#!/usr/bin/env python3
''' This module defines a function '''


async def async_comprehension():
    ''' returns an list of numbers generated by the imported function '''

    gen = __import__('0-async_generator').async_generator
    return [i async for i in gen()]
