#!/usr/bin/env python3
''' This defines a function '''

from typing import List


async def async_comprehension() -> List[float]:
    ''' returns an list of numbers generated by the imported function '''

    gen = __import__('0-async_generator').async_generator
    return [i async for i in gen()]
